// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNP4-1AvzCei2nku7thJlAw9by-I5moYQ',
    appId: '1:96740491289:web:b6a0720a5196c7f2ddea88',
    messagingSenderId: '96740491289',
    projectId: 'ecocredit-3c7b4',
    authDomain: 'ecocredit-3c7b4.firebaseapp.com',
    storageBucket: 'ecocredit-3c7b4.firebasestorage.app',
    measurementId: 'G-615CYKXMQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAeH1zZ7Ukff6LrDkGi8kqw8OPhNEXtqQ',
    appId: '1:96740491289:android:4373f8d2fa08b94eddea88',
    messagingSenderId: '96740491289',
    projectId: 'ecocredit-3c7b4',
    storageBucket: 'ecocredit-3c7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26n1vnUiUJMTh0cVCOTF0U8O4OrmKNeY',
    appId: '1:96740491289:ios:b5755fd7d9a7e9e3ddea88',
    messagingSenderId: '96740491289',
    projectId: 'ecocredit-3c7b4',
    storageBucket: 'ecocredit-3c7b4.firebasestorage.app',
    iosBundleId: 'com.example.ecoCredit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26n1vnUiUJMTh0cVCOTF0U8O4OrmKNeY',
    appId: '1:96740491289:ios:b5755fd7d9a7e9e3ddea88',
    messagingSenderId: '96740491289',
    projectId: 'ecocredit-3c7b4',
    storageBucket: 'ecocredit-3c7b4.firebasestorage.app',
    iosBundleId: 'com.example.ecoCredit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNP4-1AvzCei2nku7thJlAw9by-I5moYQ',
    appId: '1:96740491289:web:dfc974496ff79441ddea88',
    messagingSenderId: '96740491289',
    projectId: 'ecocredit-3c7b4',
    authDomain: 'ecocredit-3c7b4.firebaseapp.com',
    storageBucket: 'ecocredit-3c7b4.firebasestorage.app',
    measurementId: 'G-6M5QRB98QP',
  );
}
